Fix import queue.Empty, fix task_done call on empty queue
albertomr86/python-logging-rabbitmq pull request #32
Opened 2022-07-20 13:26 UTC by dborenko

2022-08-19 16:43 UTC, albertomr86 commented
Thank you for contributing. 
I will review it over the weekend and run some tests before releasing the final version.

2022-10-19 13:48 UTC, kmacpher67 commented
I'm not a python developer but it looks like this the key happiness for the MR: 
I'm getting this error also. Is there a best practices for using this like closing a channel or something when done or the program closes. 
                finally:
                    if not hasattr(self, 'queue'):
                        self.queue.task_done()

2023-09-26 03:52 UTC, albertomr86 requested changes
Thank you for opening the PR. Please address the comments.

2023-09-26 03:52 UTC, albertomr86 commented on python_logging_rabbitmq/handlers_oneway.py
> +            rabbitmq_logger.setlevel(rabbitmq_logger_level)
@dborenko Can you change `setlevel` to `setLevel`? Typo (capital `L`).

2023-09-26 03:52 UTC, albertomr86 commented on python_logging_rabbitmq/handlers_oneway.py
> +                    if not hasattr(self, 'queue'):
We want to call `task_done()` if there is a queue instance. Remove the `not` operator to be:

```python
if hasattr(self, 'queue'):
    self.queue.task_done()
```

2023-09-26 23:57 UTC, albertomr86 commented
Changed merged by #37

2023-09-26 23:57 UTC, closed without merging